### ISSUE TITLE
Rendering of response schemas is odd

### ISSUE THREAD

**Issue by NfNitLoop** [SoraKumo001/openapi-to-md#7]
with a response like this:

```yaml
        '200':
          content:
            application/protobuf3: 
              schema:
                description: |
                  A protobuf `ItemList`.

                  See: <https://github.com/NfNitLoop/feoblog/blob/develop/protobufs/feoblog.proto>
                type: string
                format: binary
          description: ""
```

I get markdown like this:

```md
#### Responses

- 200 

`application/protobuf3`

```ts
{
  "description": "A protobuf `ItemList`.\n\nSee: <https://github.com/NfNitLoop/feoblog/blob/develop/protobufs/feoblog.proto>\n",
  "type": "string",
  "format": "binary"
}
```

I'm not sure if that's expected, but I was expecting the schema & Description to get pulled out and documented.
